# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160315_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-added_at']},
        ),
    ]
